services:
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3333:3333"
    depends_on:
      - db_prod
      - rabbitmq
      - minio

  db_prod:
    image: postgres:latest
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
    ports:
      - "3337:5432"

  db_test:
    image: postgres:latest
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
      - POSTGRES_DB=${POSTGRES_DB_TEST}
    ports:
      - "3335:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Porta do RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001" # Porta do WebUi do minIO
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: minio server /data  --console-address :9001 # Precisa inserir este comando para mapear a porta do WebUi e iniciar o minIO
    volumes:
      - minio_data:/data

volumes:
  pgdata_prod:
  pgdata_test:
  rabbitmq_data:
  minio_data:
