services:
  db_prod:
    image: postgres:latest
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
    ports:
      - "3337:5432"

  db_test:
    image: postgres:latest
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
      - POSTGRES_DB=${POSTGRES_DB_TEST}
    ports:
      - "3335:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Porta do RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  pgdata_prod:
  pgdata_test:
